"""Beautiful PDF report generator using WeasyPrint + Jinja2.

Renders professional-quality PDF reports from Markdown content with
configurable themes (professional, minimal, academic), table of contents,
page numbers, cover pages, and data-driven chart injection.
"""

from __future__ import annotations

import base64
import html as _html
import io
import ipaddress
import logging
import re
import socket
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

logger = logging.getLogger(__name__)

# Optional dependencies - graceful degradation
try:
    from weasyprint import HTML as WeasyprintHTML

    HAS_WEASYPRINT = True
except ImportError:
    WeasyprintHTML = None  # type: ignore[assignment,misc]
    HAS_WEASYPRINT = False
    logger.info("weasyprint not available - install sandcastle-ai[report]")

try:
    import markdown as md_lib

    HAS_MARKDOWN = True
except ImportError:
    md_lib = None  # type: ignore[assignment]
    HAS_MARKDOWN = False

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    HAS_MATPLOTLIB = True
except ImportError:
    plt = None  # type: ignore[assignment]
    HAS_MATPLOTLIB = False

try:
    from jinja2 import Template as Jinja2Template

    HAS_JINJA2 = True
except ImportError:
    Jinja2Template = None  # type: ignore[assignment,misc]
    HAS_JINJA2 = False


# ---------------------------------------------------------------------------
# Themes - Professional-grade CSS
# ---------------------------------------------------------------------------

_PROFESSIONAL_CSS = """\
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');

@page {{
    size: {paper_size};
    margin: 2.5cm 2cm 2.5cm 2cm;
    border-top: 2px solid {accent};
    @bottom-center {{
        content: {page_counter};
        font-size: 9pt;
        color: #6b7280;
        font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    }}
    @bottom-right {{
        content: "Generated by Sandcastle";
        font-size: 7pt;
        color: #d1d5db;
        font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    }}
    @top-right {{
        content: string(doc-title);
        font-size: 8pt;
        color: #9ca3af;
        font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    }}
}}

@page :first {{
    border-top: none;
    @bottom-center {{ content: none; }}
    @bottom-right {{ content: none; }}
    @top-right {{ content: none; }}
}}

:root {{
    --accent: {accent};
    --accent-light: {accent}1a;
    --accent-border: {accent}40;
}}

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    font-size: 10.5pt;
    line-height: 1.75;
    color: #1f2937;
    -webkit-font-smoothing: antialiased;
}}

/* -- Cover page --------------------------------------------------------- */

.cover {{
    page-break-after: always;
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 90vh;
    padding: 3cm 0;
    position: relative;
}}

.cover::before {{
    content: "";
    position: absolute;
    top: -2.5cm;
    left: -2cm;
    right: -2cm;
    height: 8px;
    background: var(--accent);
}}

.cover-tag {{
    display: inline-block;
    font-size: 8pt;
    font-weight: 700;
    color: var(--accent);
    text-transform: uppercase;
    letter-spacing: 0.15em;
    border: 1.5px solid var(--accent);
    padding: 0.1cm 0.4cm;
    border-radius: 3px;
    margin-bottom: 1cm;
}}

.cover-accent {{
    width: 80px;
    height: 5px;
    background: var(--accent);
    border-radius: 3px;
    margin-bottom: 1.5cm;
}}

.cover h1 {{
    string-set: doc-title content();
    font-size: 32pt;
    font-weight: 800;
    color: #111827;
    line-height: 1.12;
    letter-spacing: -0.03em;
    margin-bottom: 0.5cm;
}}

.cover .subtitle {{
    font-size: 13pt;
    font-weight: 400;
    color: #6b7280;
    line-height: 1.5;
    margin-bottom: 2cm;
    max-width: 85%;
}}

.cover .meta {{
    font-size: 10pt;
    color: #9ca3af;
    line-height: 1.8;
    border-top: 1px solid #e5e7eb;
    padding-top: 0.5cm;
}}

.cover .meta strong {{
    color: #6b7280;
    font-weight: 600;
}}

.cover .logo {{
    max-width: 120px;
    max-height: 60px;
    margin-bottom: 1cm;
}}

/* -- Table of Contents -------------------------------------------------- */

.toc {{
    page-break-after: always;
    padding-top: 1cm;
}}

.toc h2 {{
    font-size: 16pt;
    font-weight: 700;
    color: #111827;
    margin-bottom: 0.8cm;
    padding-bottom: 0.3cm;
    border-bottom: 2px solid var(--accent);
}}

.toc ul {{
    list-style: none;
    padding: 0;
}}

.toc li {{
    padding: 0.25cm 0;
    border-bottom: 1px solid #f3f4f6;
}}

.toc li a {{
    text-decoration: none;
    color: #374151;
    font-size: 10.5pt;
    display: flex;
    justify-content: space-between;
    align-items: baseline;
}}

.toc li a:hover {{
    color: var(--accent);
}}

.toc li a .dots {{
    flex: 1;
    border-bottom: 1px dotted #d1d5db;
    margin: 0 0.3cm;
    min-width: 2cm;
}}

.toc .toc-h3 {{
    padding-left: 1cm;
}}

.toc .toc-h3 a {{
    font-size: 9.5pt;
    color: #6b7280;
}}

/* -- Headings ----------------------------------------------------------- */

h2 {{
    font-size: 16pt;
    font-weight: 700;
    color: #111827;
    margin-top: 1.2cm;
    margin-bottom: 0.5cm;
    padding-bottom: 0.25cm;
    border-bottom: 2px solid var(--accent);
    page-break-before: auto;
    page-break-after: avoid;
    letter-spacing: -0.02em;
}}

h2:first-of-type {{
    page-break-before: avoid;
}}

.content {{
    orphans: 3;
    widows: 3;
}}

.content > * {{
    page-break-inside: avoid;
}}

h3 {{
    font-size: 12.5pt;
    font-weight: 600;
    color: #374151;
    margin-top: 0.8cm;
    margin-bottom: 0.3cm;
    padding-left: 0.3cm;
    border-left: 3px solid var(--accent);
    page-break-after: avoid;
}}

h4 {{
    font-size: 11pt;
    font-weight: 600;
    color: #4b5563;
    margin-top: 0.6cm;
    margin-bottom: 0.2cm;
    page-break-after: avoid;
}}

/* -- Body elements ------------------------------------------------------ */

p {{
    margin-bottom: 0.45cm;
    text-align: justify;
    hyphens: auto;
    orphans: 3;
    widows: 3;
}}

/* Drop caps removed - causes rendering issues in WeasyPrint */

ul {{
    margin-bottom: 0.45cm;
    padding-left: 1cm;
    list-style: none;
}}

.content ul li {{
    margin-bottom: 0.15cm;
    list-style-type: disc;
    color: var(--accent);
}}

.content ul li * {{
    color: #1f2937;
}}

.content ol {{
    margin-bottom: 0.45cm;
    padding-left: 1cm;
    list-style: none;
    counter-reset: ol-counter;
}}

.content ol li {{
    margin-bottom: 0.15cm;
    padding-left: 0.5cm;
    position: relative;
    counter-increment: ol-counter;
}}

.content ol li::before {{
    content: counter(ol-counter) ".";
    color: var(--accent);
    font-weight: 700;
    font-size: 0.95em;
    position: absolute;
    left: -0.6cm;
    top: 0;
}}

strong {{
    font-weight: 700;
    color: var(--accent);
}}

em {{
    font-style: italic;
    color: #4b5563;
}}

a {{
    color: var(--accent);
    text-decoration: none;
    border-bottom: 1px solid var(--accent-border);
}}

/* -- Blockquotes (key findings) ---------------------------------------- */

blockquote {{
    margin: 0.6cm 0;
    padding: 0.5cm 0.8cm 0.5cm 1cm;
    background: var(--accent-light);
    border-left: 4px solid var(--accent);
    border-radius: 0 6px 6px 0;
    font-style: italic;
    color: #374151;
    page-break-inside: avoid;
    position: relative;
}}

/* Decorative quote removed - Unicode rendering issues in WeasyPrint */

blockquote p {{
    margin-bottom: 0.1cm;
    text-align: left;
    padding-left: 0.3cm;
}}

blockquote p:last-child {{
    margin-bottom: 0;
}}

/* -- Code blocks -------------------------------------------------------- */

code {{
    font-family: "JetBrains Mono", "Fira Code", "SF Mono", "Cascadia Code", monospace;
    font-size: 9pt;
    background: #f3f4f6;
    padding: 0.08cm 0.2cm;
    border-radius: 3px;
    color: #be185d;
}}

pre {{
    margin: 0.5cm 0;
    padding: 0.6cm 0.8cm;
    background: #1f2937;
    color: #e5e7eb;
    border-radius: 8px;
    overflow-x: auto;
    font-size: 8.5pt;
    line-height: 1.6;
    page-break-inside: avoid;
    border-left: 4px solid var(--accent);
}}

pre code {{
    background: none;
    padding: 0;
    color: inherit;
    font-size: inherit;
}}

/* -- Tables ------------------------------------------------------------- */

table {{
    width: 100%;
    border-collapse: collapse;
    margin: 0.6cm 0;
    font-size: 9.5pt;
    page-break-inside: avoid;
    border-left: 3px solid var(--accent);
}}

caption {{
    caption-side: top;
    text-align: left;
    font-size: 9pt;
    font-weight: 600;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.2cm;
    padding-left: 0.1cm;
}}

thead {{
    background: #f9fafb;
}}

th {{
    padding: 0.3cm 0.4cm;
    text-align: left;
    font-weight: 700;
    color: #374151;
    border-bottom: 2px solid #e5e7eb;
    font-size: 8.5pt;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}}

td {{
    padding: 0.3cm 0.4cm;
    border-bottom: 1px solid #f3f4f6;
    color: #4b5563;
    vertical-align: top;
}}

tbody tr:nth-child(even) {{
    background: #f9fafb;
}}

tbody tr:nth-child(odd) {{
    background: #ffffff;
}}

/* -- Horizontal rule ---------------------------------------------------- */

hr {{
    border: none;
    height: 1px;
    margin: 0.8cm 0;
    background: linear-gradient(to right, var(--accent), #e5e7eb, transparent);
}}

/* -- Chart images ------------------------------------------------------- */

.chart-container {{
    text-align: center;
    margin: 0.6cm 0;
    page-break-inside: avoid;
}}

.chart-container img {{
    max-width: 100%;
    height: auto;
}}

/* -- Auto-generated charts ---------------------------------------------- */

.chart {{
    margin: 0.5cm 0;
    text-align: center;
    page-break-inside: avoid;
}}

.chart img {{
    max-width: 100%;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
}}

.chart-caption {{
    font-size: 8.5pt;
    color: #6b7280;
    font-style: italic;
    margin-top: 0.2cm;
}}

/* -- KPI / metric boxes ------------------------------------------------- */

.metric-row {{
    display: flex;
    gap: 1cm;
    margin: 0.5cm 0 0.8cm;
}}

.metric-box {{
    flex: 1;
    text-align: center;
    padding: 0.5cm;
    background: #f8f9fa;
    border-radius: 6px;
    border-top: 3px solid var(--accent);
}}

.metric-value {{
    font-size: 18pt;
    font-weight: 800;
    color: var(--accent);
}}

.metric-label {{
    font-size: 8pt;
    color: #6b7280;
    margin-top: 0.1cm;
}}

/* -- Callout boxes ------------------------------------------------------ */

.callout {{
    margin: 0.5cm 0;
    padding: 0.5cm 0.8cm 0.5cm 1cm;
    border-radius: 6px;
    page-break-inside: avoid;
    position: relative;
    padding-left: 1.4cm;
}}

.callout::before {{
    position: absolute;
    left: 0.4cm;
    top: 0.5cm;
    font-size: 14pt;
}}

.callout-info {{
    background: #eff6ff;
    border-left: 4px solid #3b82f6;
    color: #1e40af;
}}

.callout-info::before {{
    content: "i";
    font-weight: 800;
    font-style: italic;
    font-family: serif;
    color: #3b82f6;
}}

.callout-warning {{
    background: #fffbeb;
    border-left: 4px solid #f59e0b;
    color: #92400e;
}}

.callout-warning::before {{
    content: "!";
    font-weight: 800;
    color: #f59e0b;
}}

.callout-success {{
    background: #f0fdf4;
    border-left: 4px solid #10b981;
    color: #065f46;
}}

.callout-success::before {{
    content: "";
    color: #10b981;
}}

.callout p {{
    margin-bottom: 0.15cm;
    text-align: left;
    color: inherit;
}}

.callout p:last-child {{
    margin-bottom: 0;
}}

/* -- Styled dividers ---------------------------------------------------- */

.styled-divider {{
    display: flex;
    align-items: center;
    margin: 1cm 0;
    page-break-inside: avoid;
    page-break-after: avoid;
}}

.styled-divider::before,
.styled-divider::after {{
    content: "";
    flex: 1;
    height: 1px;
    background: linear-gradient(to right, transparent, var(--accent), transparent);
}}

.styled-divider span {{
    padding: 0 0.5cm;
    font-size: 9pt;
    font-weight: 600;
    color: var(--accent);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    white-space: nowrap;
}}
"""

_MINIMAL_CSS = """\
@import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400&display=swap');

@page {{
    size: {paper_size};
    margin: 2cm;
    @bottom-center {{
        content: {page_counter};
        font-size: 8pt;
        color: #999;
    }}
}}

@page :first {{
    @bottom-center {{ content: none; }}
}}

body {{
    font-family: "Lora", "Georgia", "Times New Roman", "DejaVu Serif", serif;
    font-size: 11pt;
    line-height: 1.8;
    color: #333;
    max-width: 100%;
}}

.cover {{
    page-break-after: always;
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 80vh;
    text-align: center;
    padding: 4cm 2cm;
}}

.cover-accent {{
    width: 40px;
    height: 2px;
    background: {accent};
    margin: 0 auto 2cm auto;
}}

.cover h1 {{
    font-size: 24pt;
    font-weight: 400;
    color: #111;
    letter-spacing: -0.01em;
    margin-bottom: 0.5cm;
}}

.cover .subtitle {{
    font-size: 12pt;
    color: #666;
    font-style: italic;
    margin-bottom: 1.5cm;
}}

.cover .meta {{
    font-size: 9.5pt;
    color: #999;
}}

.cover .logo {{ max-width: 80px; margin: 0 auto 1cm auto; }}

.toc {{ page-break-after: always; }}
.toc h2 {{ font-size: 14pt; font-weight: 400; color: #111; margin-bottom: 0.6cm; }}
.toc ul {{ list-style: none; padding: 0; }}
.toc li {{ padding: 0.2cm 0; }}
.toc li a {{ text-decoration: none; color: #333; }}
.toc .toc-h3 {{ padding-left: 1.2cm; }}
.toc .toc-h3 a {{ color: #888; font-size: 10pt; }}

h2 {{
    font-size: 15pt;
    font-weight: 400;
    color: #111;
    margin-top: 1cm;
    margin-bottom: 0.4cm;
    page-break-before: always;
    border-bottom: 1px solid #ddd;
    padding-bottom: 0.2cm;
}}
h2:first-of-type {{ page-break-before: avoid; }}

h3 {{ font-size: 12pt; font-weight: 700; color: #333; margin-top: 0.7cm; margin-bottom: 0.3cm; }}
h4 {{ font-size: 11pt; font-weight: 700; color: #555; margin-top: 0.5cm; margin-bottom: 0.2cm; }}

p {{ margin-bottom: 0.4cm; }}
blockquote {{
    margin: 0.5cm 0; padding: 0.4cm 0.6cm;
    border-left: 2px solid #ddd; color: #555; font-style: italic;
}}

code {{ font-family: monospace; font-size: 9.5pt; background: #f5f5f5; padding: 0.05cm 0.15cm; }}
pre {{ background: #f5f5f5; padding: 0.5cm; border-radius: 3px; font-size: 8.5pt; margin: 0.4cm 0; }}
pre code {{ background: none; padding: 0; }}

table {{ width: 100%; border-collapse: collapse; margin: 0.4cm 0; font-size: 9.5pt; }}
th {{ padding: 0.2cm 0.3cm; text-align: left; font-weight: 700; border-bottom: 2px solid #ddd; }}
td {{ padding: 0.2cm 0.3cm; border-bottom: 1px solid #eee; }}
tbody tr:nth-child(even) {{ background: #fafafa; }}
hr {{ border: none; border-top: 1px solid #eee; margin: 0.6cm 0; }}

ul, ol {{ margin-bottom: 0.4cm; padding-left: 1cm; }}
li {{ margin-bottom: 0.1cm; }}
strong {{ font-weight: 700; }}

.chart-container {{ text-align: center; margin: 0.5cm 0; }}
.chart-container img {{ max-width: 100%; }}

.chart {{ margin: 0.5cm 0; text-align: center; page-break-inside: avoid; }}
.chart img {{ max-width: 100%; border: 1px solid #e5e7eb; border-radius: 6px; }}
.chart-caption {{ font-size: 8.5pt; color: #888; font-style: italic; margin-top: 0.2cm; }}

.metric-row {{ display: flex; gap: 0.8cm; margin: 0.4cm 0 0.6cm; }}
.metric-box {{ flex: 1; text-align: center; padding: 0.4cm; background: #fafafa; border-radius: 4px; border-top: 2px solid {accent}; }}
.metric-value {{ font-size: 16pt; font-weight: 700; color: {accent}; }}
.metric-label {{ font-size: 8pt; color: #888; margin-top: 0.1cm; }}

.callout {{ margin: 0.4cm 0; padding: 0.4cm 0.6cm 0.4cm 1.2cm; border-radius: 4px; page-break-inside: avoid; position: relative; }}
.callout::before {{ position: absolute; left: 0.3cm; top: 0.4cm; font-size: 13pt; }}
.callout-info {{ background: #f0f4ff; border-left: 3px solid #3b82f6; color: #1e40af; }}
.callout-info::before {{ content: "i"; font-weight: 800; font-style: italic; font-family: serif; color: #3b82f6; }}
.callout-warning {{ background: #fffbeb; border-left: 3px solid #f59e0b; color: #92400e; }}
.callout-warning::before {{ content: "!"; font-weight: 800; color: #f59e0b; }}
.callout-success {{ background: #f0fdf4; border-left: 3px solid #10b981; color: #065f46; }}
.callout-success::before {{ content: ""; color: #10b981; }}
.callout p {{ margin-bottom: 0.1cm; text-align: left; color: inherit; }}
.callout p:last-child {{ margin-bottom: 0; }}

.styled-divider {{ display: flex; align-items: center; margin: 0.8cm 0; }}
.styled-divider::before, .styled-divider::after {{ content: ""; flex: 1; height: 1px; background: #ddd; }}
.styled-divider span {{ padding: 0 0.4cm; font-size: 9pt; font-weight: 600; color: #666; white-space: nowrap; }}
"""

_ACADEMIC_CSS = """\
@import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400&display=swap');

@page {{
    size: {paper_size};
    margin: 2.5cm;
    @bottom-center {{
        content: {page_counter};
        font-size: 10pt;
        font-family: "Lora", "Times New Roman", "DejaVu Serif", Georgia, serif;
    }}
    @top-left {{
        content: string(doc-title);
        font-size: 9pt;
        color: #666;
        font-family: "Lora", "Times New Roman", "DejaVu Serif", Georgia, serif;
        font-style: italic;
    }}
}}

@page :first {{
    @bottom-center {{ content: none; }}
    @top-left {{ content: none; }}
}}

body {{
    font-family: "Lora", "Times New Roman", "DejaVu Serif", Georgia, serif;
    font-size: 12pt;
    line-height: 2;
    color: #000;
}}

.cover {{
    page-break-after: always;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 85vh;
    text-align: center;
    padding: 4cm 2cm;
}}

.cover-accent {{
    display: none;
}}

.cover h1 {{
    string-set: doc-title content();
    font-size: 18pt;
    font-weight: 700;
    color: #000;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.5cm;
}}

.cover .subtitle {{
    font-size: 14pt;
    color: #333;
    margin-bottom: 2cm;
}}

.cover .meta {{
    font-size: 11pt;
    color: #333;
    line-height: 2.2;
}}

.cover .logo {{ max-width: 100px; margin-bottom: 1.5cm; }}

.toc {{ page-break-after: always; }}
.toc h2 {{ font-size: 14pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.5cm; text-align: center; }}
.toc ul {{ list-style: none; padding: 0; }}
.toc li {{ padding: 0.15cm 0; }}
.toc li a {{ text-decoration: none; color: #000; display: flex; justify-content: space-between; }}
.toc li a .dots {{ flex: 1; border-bottom: 1px dotted #999; margin: 0 0.3cm; }}
.toc .toc-h3 {{ padding-left: 1.5cm; }}
.toc .toc-h3 a {{ font-size: 11pt; }}

h2 {{
    font-size: 14pt;
    font-weight: 700;
    color: #000;
    margin-top: 1cm;
    margin-bottom: 0.4cm;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    text-align: center;
    page-break-before: always;
}}
h2:first-of-type {{ page-break-before: avoid; }}

h3 {{
    font-size: 12pt;
    font-weight: 700;
    color: #000;
    margin-top: 0.6cm;
    margin-bottom: 0.3cm;
    font-style: italic;
}}

h4 {{
    font-size: 12pt;
    font-weight: 400;
    font-style: italic;
    color: #333;
    margin-top: 0.5cm;
    margin-bottom: 0.2cm;
}}

p {{
    margin-bottom: 0;
    text-indent: 1.5cm;
    text-align: justify;
    hyphens: auto;
    orphans: 3;
    widows: 3;
}}

p:first-of-type,
h2 + p, h3 + p, h4 + p,
blockquote + p,
ul + p, ol + p, pre + p {{
    text-indent: 0;
}}

blockquote {{
    margin: 0.5cm 1cm;
    padding: 0;
    border: none;
    font-style: italic;
    color: #333;
}}

blockquote p {{
    text-indent: 0;
    font-size: 11pt;
    line-height: 2;
}}

code {{ font-family: "Courier New", monospace; font-size: 10pt; }}
pre {{
    margin: 0.4cm 0;
    padding: 0.4cm 0.6cm;
    border: 1px solid #ccc;
    font-size: 9pt;
    line-height: 1.5;
}}
pre code {{ font-size: inherit; }}

table {{ width: 100%; border-collapse: collapse; margin: 0.5cm 0; font-size: 10pt; }}
th, td {{ padding: 0.2cm 0.3cm; border: 1px solid #999; }}
th {{ font-weight: 700; text-align: center; }}

hr {{ border: none; border-top: 1px solid #ccc; margin: 0.5cm 0; }}

ul, ol {{ margin-bottom: 0.3cm; padding-left: 1.5cm; }}
li {{ margin-bottom: 0.05cm; }}
strong {{ font-weight: 700; }}

.chart-container {{ text-align: center; margin: 0.5cm 0; }}
.chart-container img {{ max-width: 100%; }}

.chart {{ margin: 0.5cm 0; text-align: center; page-break-inside: avoid; }}
.chart img {{ max-width: 100%; border: 1px solid #ccc; }}
.chart-caption {{ font-size: 9pt; color: #666; font-style: italic; margin-top: 0.2cm; }}

.metric-row {{ display: flex; gap: 0.8cm; margin: 0.4cm 0 0.6cm; }}
.metric-box {{ flex: 1; text-align: center; padding: 0.4cm; border: 1px solid #ccc; }}
.metric-value {{ font-size: 16pt; font-weight: 700; color: #000; }}
.metric-label {{ font-size: 9pt; color: #666; margin-top: 0.1cm; }}

.callout {{ margin: 0.4cm 0; padding: 0.4cm 0.6cm 0.4cm 1.2cm; page-break-inside: avoid; position: relative; border: 1px solid #ccc; }}
.callout::before {{ position: absolute; left: 0.3cm; top: 0.4cm; font-size: 13pt; }}
.callout-info {{ border-left: 3px solid #333; }}
.callout-info::before {{ content: "\\2139"; color: #333; }}
.callout-warning {{ border-left: 3px solid #666; }}
.callout-warning::before {{ content: "\\26A0"; color: #666; }}
.callout-success {{ border-left: 3px solid #333; }}
.callout-success::before {{ content: "\\2713"; color: #333; }}
.callout p {{ margin-bottom: 0.1cm; text-indent: 0; text-align: left; color: inherit; }}
.callout p:last-child {{ margin-bottom: 0; }}

.styled-divider {{ display: flex; align-items: center; margin: 0.8cm 0; }}
.styled-divider::before, .styled-divider::after {{ content: ""; flex: 1; height: 1px; background: #ccc; }}
.styled-divider span {{ padding: 0 0.4cm; font-size: 10pt; font-weight: 700; color: #333; text-transform: uppercase; white-space: nowrap; }}
"""

_THEME_CSS = {
    "professional": _PROFESSIONAL_CSS,
    "minimal": _MINIMAL_CSS,
    "academic": _ACADEMIC_CSS,
}


# ---------------------------------------------------------------------------
# HTML template (shared across themes - CSS provides the look)
# ---------------------------------------------------------------------------

_REPORT_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
{css}
</style>
</head>
<body>

<div class="cover">
{logo_html}
<div class="cover-tag">Report</div>
<div class="cover-accent"></div>
<h1>{title}</h1>
{subtitle_html}
<div class="meta">
{author_html}
<span>{date}</span>
</div>
</div>

{toc_html}

<div class="content">
{content}
</div>

</body>
</html>
"""


# ---------------------------------------------------------------------------
# Markdown to HTML conversion
# ---------------------------------------------------------------------------

def _markdown_to_html(text: str) -> str:
    """Convert Markdown content to HTML.

    Uses the ``markdown`` library with tables, fenced_code, and toc
    extensions when available, otherwise falls back to a basic regex
    converter.
    """
    if HAS_MARKDOWN:
        return md_lib.markdown(
            text,
            extensions=["tables", "fenced_code", "toc", "smarty", "nl2br"],
        )
    # Minimal fallback: headings, bold, italic, code blocks, paragraphs
    html = text

    # Fenced code blocks (```lang ... ```)
    def _replace_code_block(m: re.Match) -> str:
        lang = m.group(1) or ""
        code = m.group(2)
        cls = f' class="language-{lang}"' if lang else ""
        escaped = code.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"<pre><code{cls}>{escaped}</code></pre>"

    html = re.sub(r"^```(\w*)\n(.*?)^```", _replace_code_block, html, flags=re.MULTILINE | re.DOTALL)

    html = re.sub(r"^#### (.+)$", r"<h4>\1</h4>", html, flags=re.MULTILINE)
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
    # Wrap remaining bare lines in <p>
    lines = html.split("\n")
    result: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            result.append("")
        elif stripped.startswith("<"):
            result.append(stripped)
        else:
            result.append(f"<p>{stripped}</p>")
    return "\n".join(result)


# ---------------------------------------------------------------------------
# Table of Contents builder
# ---------------------------------------------------------------------------

def _build_toc(html: str) -> tuple[str, str]:
    """Extract h2/h3 headings from HTML and build a ToC block.

    Returns (toc_html, modified_html_with_ids).
    """
    heading_pattern = re.compile(r"<(h[23])(?:\s[^>]*)?>(.+?)</\1>", re.IGNORECASE)
    entries: list[tuple[str, str, str]] = []  # (level, id, text)
    counter = 0

    def _add_id(m: re.Match) -> str:
        nonlocal counter
        tag = m.group(1).lower()
        text = re.sub(r"<[^>]+>", "", m.group(2)).strip()
        anchor = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
        if not anchor:
            anchor = f"section-{counter}"
        anchor = f"{anchor}-{counter}"
        counter += 1
        entries.append((tag, anchor, text))
        return f'<{tag} id="{anchor}">{m.group(2)}</{tag}>'

    modified_html = heading_pattern.sub(_add_id, html)

    if not entries:
        return "", modified_html

    toc_lines = ['<div class="toc">', "<h2>Table of Contents</h2>", "<ul>"]
    for level, anchor, text in entries:
        css_class = "toc-h3" if level == "h3" else "toc-h2"
        toc_lines.append(
            f'<li class="{css_class}">'
            f'<a href="#{anchor}">{text}<span class="dots"></span>'
            f'</a>'
            f"</li>"
        )
    toc_lines.append("</ul>")
    toc_lines.append("</div>")

    return "\n".join(toc_lines), modified_html


# ---------------------------------------------------------------------------
# Chart injection (matplotlib data patterns -> base64 SVG)
# ---------------------------------------------------------------------------

def _inject_charts(html: str, metadata: dict[str, Any]) -> str:
    """Find data patterns in the content and replace with rendered chart images.

    Looks for fenced code blocks with language ``chart`` or ``data`` and
    attempts to render them as matplotlib figures encoded as base64 PNG.
    """
    if not HAS_MATPLOTLIB:
        return html

    chart_pattern = re.compile(
        r'<pre><code class="language-chart">(.*?)</code></pre>',
        re.DOTALL,
    )

    def _render_chart(m: re.Match) -> str:
        spec = m.group(1).strip()
        try:
            import json

            data = json.loads(spec)
            chart_type = data.get("type", "bar")
            labels = data.get("labels", [])
            values = data.get("values", [])
            title = data.get("title", "")
            accent = metadata.get("accent_color", "#f59e0b")

            fig, ax = plt.subplots(figsize=(6, 3.5), dpi=150)
            fig.patch.set_facecolor("white")

            if chart_type == "pie" and labels and values:
                colors = _generate_palette(accent, len(labels))
                ax.pie(values, labels=labels, colors=colors, autopct="%1.1f%%",
                       startangle=90, textprops={"fontsize": 8})
            elif chart_type == "line" and values:
                ax.plot(labels or list(range(len(values))), values,
                        color=accent, linewidth=2, marker="o", markersize=4)
                ax.grid(True, alpha=0.3)
            else:
                # Default bar chart
                colors = _generate_palette(accent, len(values))
                bars = ax.bar(labels or list(range(len(values))), values, color=colors)
                ax.grid(True, axis="y", alpha=0.3)

            if title:
                ax.set_title(title, fontsize=11, fontweight="bold", pad=10)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            fig.tight_layout()

            buf = io.BytesIO()
            fig.savefig(buf, format="png", bbox_inches="tight", facecolor="white")
            plt.close(fig)
            buf.seek(0)
            b64 = base64.b64encode(buf.read()).decode()
            return (
                f'<div class="chart-container">'
                f'<img src="data:image/png;base64,{b64}" alt="{title}">'
                f"</div>"
            )
        except Exception as exc:
            logger.warning("Chart rendering failed: %s", exc)
            return m.group(0)  # Keep original on failure

    return chart_pattern.sub(_render_chart, html)


def _generate_palette(accent: str, n: int) -> list[str]:
    """Generate n colors as tints/shades of the accent color.

    Creates a cohesive monochromatic palette instead of random colors.
    Lighter tints for less important items, darker for emphasis.
    """
    # Parse accent hex color
    acc = accent.lstrip("#")
    try:
        r, g, b = int(acc[:2], 16), int(acc[2:4], 16), int(acc[4:6], 16)
    except (ValueError, IndexError):
        r, g, b = 59, 130, 246  # fallback blue

    colors = []
    for i in range(n):
        # Vary lightness: from 30% darker to 60% lighter
        t = i / max(n - 1, 1)  # 0.0 to 1.0
        factor = 0.7 + t * 0.9  # 0.7 (darker) to 1.6 (lighter)
        nr = min(255, int(r * factor))
        ng = min(255, int(g * factor))
        nb = min(255, int(b * factor))
        colors.append(f"#{nr:02x}{ng:02x}{nb:02x}")

    return colors


# ---------------------------------------------------------------------------
# Auto-chart generation from HTML tables
# ---------------------------------------------------------------------------

def _render_chart_image(
    chart_type: str,
    labels: list[str],
    values: list[float],
    title: str,
    accent: str,
) -> str:
    """Render a matplotlib chart and return a base64-encoded PNG data URI.

    Supported chart_type values: bar, horizontal_bar, pie, line.
    Returns empty string if matplotlib is unavailable or rendering fails.
    """
    if not HAS_MATPLOTLIB:
        return ""
    try:
        # 16cm x 8cm at 150dpi for clean A4 output
        fig, ax = plt.subplots(figsize=(6.3, 3.15), dpi=150)
        fig.patch.set_facecolor("white")
        ax.set_facecolor("white")

        palette = _generate_palette(accent, len(labels))

        if chart_type == "pie":
            ax.pie(
                values,
                labels=labels,
                colors=palette,
                autopct="%1.1f%%",
                startangle=90,
                textprops={"fontsize": 8},
            )
        elif chart_type == "line":
            ax.plot(
                labels,
                values,
                color=accent,
                linewidth=2,
                marker="o",
                markersize=5,
            )
            ax.tick_params(axis="x", rotation=30, labelsize=8)
            ax.tick_params(axis="y", labelsize=8)
        elif chart_type == "horizontal_bar":
            y_pos = range(len(labels))
            ax.barh(y_pos, values, color=palette)
            ax.set_yticks(y_pos)
            ax.set_yticklabels(labels, fontsize=8)
            ax.tick_params(axis="x", labelsize=8)
            ax.invert_yaxis()
        else:
            # Default: vertical bar
            x_pos = range(len(labels))
            ax.bar(x_pos, values, color=palette)
            ax.set_xticks(x_pos)
            ax.set_xticklabels(labels, fontsize=8, rotation=30, ha="right")
            ax.tick_params(axis="y", labelsize=8)

        if title:
            ax.set_title(title, fontsize=10, fontweight="bold", pad=10)

        # Readable number formatting (no scientific notation like 1e6)
        if chart_type not in ("pie",):
            from matplotlib.ticker import FuncFormatter
            def _fmt_number(x, _pos):
                if abs(x) >= 1_000_000:
                    return f"{x/1_000_000:.1f} mil."
                if abs(x) >= 1_000:
                    return f"{x/1_000:.0f} tis."
                return f"{x:.0f}"
            ax.yaxis.set_major_formatter(FuncFormatter(_fmt_number))
            if chart_type == "horizontal_bar":
                ax.xaxis.set_major_formatter(FuncFormatter(_fmt_number))

        # Clean styling: remove top/right spines, no grid clutter
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        if chart_type != "pie":
            ax.spines["left"].set_linewidth(0.5)
            ax.spines["bottom"].set_linewidth(0.5)

        fig.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight", facecolor="white")
        plt.close(fig)
        buf.seek(0)
        return base64.b64encode(buf.read()).decode()
    except Exception as exc:
        logger.warning("Chart rendering failed: %s", exc)
        if "fig" in dir():
            try:
                plt.close(fig)  # type: ignore[possibly-undefined]
            except Exception:
                pass
        return ""


def _should_chart_table(headers: list[str], data_rows: list[list[str]]) -> tuple[bool, str]:
    """Decide if a table should have a chart, and which type.

    Based on data visualization best practices:
    - Bar chart: comparing discrete categories (cities, products, modes)
    - Horizontal bar: comparing when labels are long (>15 chars average)
    - Line chart: data over time (years, months, dates in first column)
    - Pie chart: composition/parts of a whole (max 6 slices, has % or podil)
    - NO chart: property tables, attribute lists, mixed non-comparable data,
      tables with <3 rows, tables where values are IDs/years/codes

    Returns (should_chart, chart_type) where chart_type is bar/horizontal_bar/line/pie.

    References:
    - https://www.datawrapper.de/blog/chart-types-guide
    - https://eazybi.com/blog/data-visualization-and-chart-types
    - https://www.atlassian.com/data/charts/essential-chart-types-for-data-visualization
    """
    if len(data_rows) < 3:
        return False, ""

    headers_lower = [h.lower() for h in headers]

    # NEVER chart these - property/attribute tables
    skip_keywords = {
        "popis", "description", "typ", "type", "nazev", "název", "name",
        "adresa", "address", "kontakt", "contact", "odkaz", "link", "url",
        "poznamka", "poznámka", "note", "moznost", "možnost", "option",
        "parametr", "parameter", "stanice", "station", "rok", "year",
        "vyrobce", "výrobce", "manufacturer", "model", "serie", "séria",
        "prestup", "přestup", "transfer", "provozovatel", "operator",
    }

    skip_count = sum(1 for h in headers_lower if any(k in h for k in skip_keywords))
    if skip_count >= len(headers) // 2:
        return False, ""

    # Check if first column contains years/dates -> line chart
    time_pattern = re.compile(r"^(19|20)\d{2}$|^\d{4}[-/]|^Q[1-4]|^(led|úno|bře|dub|kvě|čer|srp|zář|říj|lis|pro|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)", re.IGNORECASE)
    time_count = sum(1 for row in data_rows if time_pattern.match(row[0].strip()))
    if time_count >= len(data_rows) * 0.7:
        return True, "line"

    # Headers that indicate COMPARABLE metrics worth charting
    metric_keywords = {
        "počet", "pocet", "count", "celkem", "total",
        "podíl", "podil", "%", "procent",
        "mld", "mil", "tis", "kč", "kc", "eur", "usd", "czk",
        "náklady", "naklady", "cost", "cena", "price",
        "délka", "delka", "km", "length",
        "kapacita", "capacity", "cestující", "cestujici", "passengers",
        "přeprava", "preprava", "výkon", "vykon", "objem", "volume",
        "spokojenost", "satisfaction", "score", "index", "rate",
        "emise", "emission", "spotřeba", "spotreba", "consumption",
    }

    # At least one value-column header must suggest a metric
    has_metric = any(
        any(k in h for k in metric_keywords)
        for h in headers_lower[1:]
    )
    if not has_metric:
        return False, ""

    # Check if values are actually comparable numbers (not IDs, years, codes)
    first_values = []
    for row in data_rows:
        if len(row) > 1:
            cleaned = row[1].replace(",", "").replace(" ", "").replace("\xa0", "")
            cleaned = re.sub(r"[%$€]", "", cleaned)
            try:
                first_values.append(float(cleaned))
            except ValueError:
                pass

    if len(first_values) < 3:
        return False, ""

    # If all values are years (1900-2100), don't chart
    if all(1900 <= v <= 2100 for v in first_values):
        return False, ""

    # If values have very low variance (all nearly same), skip
    if max(first_values) > 0 and min(first_values) / max(first_values) > 0.95:
        return False, ""

    # Composition (% or podil) -> pie chart (max 6 slices)
    pct_keywords = {"%", "podíl", "podil", "procent", "share"}
    if any(any(k in h for k in pct_keywords) for h in headers_lower[1:]):
        if len(data_rows) <= 6:
            return True, "pie"

    # Long labels -> horizontal bar
    avg_label_len = sum(len(row[0]) for row in data_rows) / len(data_rows)
    if avg_label_len > 15:
        return True, "horizontal_bar"

    return True, "bar"


def _auto_charts_from_tables(html: str, accent: str) -> str:
    """Detect HTML tables with numeric data and inject chart images below them.

    Only generates charts for tables that represent comparable data (costs,
    counts, percentages) - NOT for property/attribute tables. Uses
    _should_chart_table() heuristic to decide.
    """
    if not HAS_MATPLOTLIB:
        return html

    table_re = re.compile(r"(<table[^>]*>.*?</table>)", re.DOTALL | re.IGNORECASE)
    figure_counter = 0
    parts: list[str] = []
    last_end = 0

    for m in table_re.finditer(html):
        parts.append(html[last_end:m.start()])
        table_html = m.group(1)
        parts.append(table_html)
        last_end = m.end()

        # Extract header cells
        th_re = re.compile(r"<th[^>]*>(.*?)</th>", re.DOTALL | re.IGNORECASE)
        headers = [re.sub(r"<[^>]+>", "", h).strip() for h in th_re.findall(table_html)]

        # Extract body rows
        row_re = re.compile(r"<tr[^>]*>(.*?)</tr>", re.DOTALL | re.IGNORECASE)
        td_re = re.compile(r"<td[^>]*>(.*?)</td>", re.DOTALL | re.IGNORECASE)
        rows_html = row_re.findall(table_html)

        data_rows: list[list[str]] = []
        for row_html in rows_html:
            cells = [re.sub(r"<[^>]+>", "", c).strip() for c in td_re.findall(row_html)]
            if cells:
                data_rows.append(cells)

        if not data_rows or not headers or len(headers) < 2:
            continue

        # Smart decision: should this table have a chart? Which type?
        should_chart, chart_type = _should_chart_table(headers, data_rows)
        if not should_chart:
            continue

        labels = [row[0] for row in data_rows]

        # Extract first numeric column values
        values: list[float] = []
        for row in data_rows:
            if len(row) > 1:
                cleaned = row[1].replace(",", "").replace(" ", "").replace("\xa0", "")
                cleaned = re.sub(r"[%$\u20ac]", "", cleaned)
                try:
                    values.append(float(cleaned))
                except ValueError:
                    values.append(0.0)

        if not values:
            continue

        chart_title = headers[1] if len(headers) > 1 else ""
        b64 = _render_chart_image(chart_type, labels, values, chart_title, accent)
        if b64:
            figure_counter += 1
            caption = f"Figure {figure_counter}: {chart_title}" if chart_title else f"Figure {figure_counter}"
            parts.append(
                f'\n<div class="chart">'
                f'<img src="data:image/png;base64,{b64}" alt="{caption}"/>'
                f'<p class="chart-caption">{caption}</p>'
                f"</div>\n"
            )

    parts.append(html[last_end:])
    return "".join(parts)


# ---------------------------------------------------------------------------
# Explicit ```chart``` fenced code block parsing
# ---------------------------------------------------------------------------

def _parse_chart_blocks(html: str, accent: str) -> str:
    """Parse explicit chart code blocks and render them as matplotlib images.

    Supports YAML-like syntax inside ``<pre><code class="language-chart">``
    blocks with keys: type, title, data (key-value pairs).
    Supported types: bar, horizontal_bar, pie, line.
    """
    if not HAS_MATPLOTLIB:
        return html

    chart_pattern = re.compile(
        r'<pre><code class="language-chart">(.*?)</code></pre>',
        re.DOTALL,
    )

    counter_holder = [0]

    def _replace_chart_block(m: re.Match) -> str:
        spec = m.group(1).strip()
        # Unescape HTML entities
        spec = spec.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")

        chart_type = "bar"
        title = ""
        data: dict[str, float] = {}

        # Parse simple YAML-like key: value format
        current_section: str | None = None
        for line in spec.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith("type:"):
                chart_type = line.split(":", 1)[1].strip()
            elif line.startswith("title:"):
                title = line.split(":", 1)[1].strip()
            elif line.startswith("data:"):
                current_section = "data"
            elif current_section == "data" and ":" in line:
                key, val = line.rsplit(":", 1)
                key = key.strip()
                val_str = val.strip().replace(",", "").replace(" ", "")
                try:
                    data[key] = float(val_str)
                except ValueError:
                    pass

        if not data:
            return m.group(0)

        labels = list(data.keys())
        values = list(data.values())

        b64 = _render_chart_image(chart_type, labels, values, title, accent)
        if not b64:
            return m.group(0)

        counter_holder[0] += 1
        caption = f"Figure {counter_holder[0]}: {title}" if title else f"Figure {counter_holder[0]}"
        return (
            f'<div class="chart">'
            f'<img src="data:image/png;base64,{b64}" alt="{caption}"/>'
            f'<p class="chart-caption">{caption}</p>'
            f"</div>"
        )

    return chart_pattern.sub(_replace_chart_block, html)


# ---------------------------------------------------------------------------
# KPI / Metric row parsing
# ---------------------------------------------------------------------------

def _parse_metric_rows(html: str) -> str:
    """Convert ``:::metric val1 | val2 | ...:::`` patterns into styled KPI boxes.

    Each segment is split by ``|``. The numeric/bold part becomes the value,
    and the remaining text becomes the label.
    """
    # Match both in raw HTML paragraphs and standalone
    pattern = re.compile(r":::metric\s+(.*?):::", re.DOTALL)

    def _replace_metric(m: re.Match) -> str:
        raw = m.group(1).strip()
        # Strip any enclosing <p>...</p> or <br/> tags
        raw = re.sub(r"<[^>]+>", " ", raw).strip()
        segments = [s.strip() for s in raw.split("|") if s.strip()]
        if not segments:
            return m.group(0)

        boxes: list[str] = []
        for seg in segments:
            # Split: first token(s) that look like a number/value, rest is label
            # Heuristic: value is everything up to the first letter-only word
            parts = seg.split(None, 1)
            if not parts:
                continue
            # Try to identify the numeric value portion
            value_parts: list[str] = []
            label_parts: list[str] = []
            found_label = False
            for word in seg.split():
                cleaned = word.replace(",", "").replace(".", "").replace("+", "").replace("%", "")
                if not found_label and (cleaned.isdigit() or word in ("mld.", "mil.", "tis.", "km", "ks", "Kc", "CZK", "EUR", "USD")):
                    value_parts.append(word)
                else:
                    found_label = True
                    label_parts.append(word)
            value = " ".join(value_parts) if value_parts else parts[0]
            label = " ".join(label_parts) if label_parts else ""
            boxes.append(
                f'<div class="metric-box">'
                f'<div class="metric-value">{value}</div>'
                f'<div class="metric-label">{label}</div>'
                f"</div>"
            )

        return f'<div class="metric-row">{"".join(boxes)}</div>'

    # Handle the pattern inside <p> tags as well
    result = re.sub(r"<p>\s*" + pattern.pattern + r"\s*</p>", lambda m: _replace_metric(m), html, flags=re.DOTALL)
    result = pattern.sub(_replace_metric, result)
    return result


# ---------------------------------------------------------------------------
# Callout box parsing
# ---------------------------------------------------------------------------

def _parse_callout_boxes(html: str) -> str:
    """Convert ``:::info``, ``:::warning``, ``:::success`` blocks into styled callouts.

    Blocks are delimited by ``:::type`` and ``:::`` on their own lines.
    """
    # These may appear as <p>:::info</p> ... <p>:::</p> in the HTML
    callout_types = ("info", "warning", "success")

    for ctype in callout_types:
        # Pattern: opening tag, content, closing tag - handle various HTML wrapping
        pattern = re.compile(
            r"(?:<p>)?\s*:::" + ctype + r"\s*(?:</p>)?\s*"
            r"(.*?)"
            r"(?:<p>)?\s*:::\s*(?:</p>)?",
            re.DOTALL,
        )

        def _make_replacer(ct: str):  # noqa: E301
            def _replace(m: re.Match) -> str:
                content = m.group(1).strip()
                # Wrap bare text in <p> if needed
                if not content.startswith("<"):
                    content = f"<p>{content}</p>"
                return f'<div class="callout callout-{ct}">{content}</div>'
            return _replace

        html = pattern.sub(_make_replacer(ctype), html)

    return html


# ---------------------------------------------------------------------------
# Styled divider parsing
# ---------------------------------------------------------------------------

def _parse_dividers(html: str) -> str:
    r"""Convert ``---{Section Break}---`` patterns into styled divider elements.

    These can appear as literal text or wrapped in ``<p>`` or ``<hr>`` tags.
    """
    # Match inside <p> tags or standalone.
    # The smarty markdown extension converts --- to &mdash; so handle both.
    dash = r"(?:---|&mdash;|\u2014)"
    pattern = re.compile(
        r"(?:<p>)?\s*" + dash + r"\{(.+?)\}" + dash + r"\s*(?:</p>)?",
        re.DOTALL,
    )

    def _replace_divider(m: re.Match) -> str:
        text = re.sub(r"<[^>]+>", "", m.group(1)).strip()
        return f'<div class="styled-divider"><span>{text}</span></div>'

    return pattern.sub(_replace_divider, html)


# ---------------------------------------------------------------------------
# Pre-markdown transformation (runs on raw markdown BEFORE conversion)
# ---------------------------------------------------------------------------

def _preprocess_markdown(text: str) -> str:
    """Transform custom syntax elements in raw markdown before HTML conversion.

    This handles patterns that would be mangled by the markdown parser,
    such as :::metric and :::callout blocks which need to pass through
    to post-processing as recognizable patterns.
    """
    # No transformations needed currently - the patterns survive markdown
    # conversion inside <p> tags which the post-processors handle.
    return text


# ---------------------------------------------------------------------------
# CSS formatting helpers
# ---------------------------------------------------------------------------

# Networks blocked when WeasyPrint fetches resources (logo, images, etc.).
# Same list as webhooks/dispatcher.py to keep the SSRF posture consistent.
_BLOCKED_NETWORKS = [
    ipaddress.ip_network("0.0.0.0/8"),
    ipaddress.ip_network("127.0.0.0/8"),
    ipaddress.ip_network("10.0.0.0/8"),
    ipaddress.ip_network("172.16.0.0/12"),
    ipaddress.ip_network("192.168.0.0/16"),
    ipaddress.ip_network("169.254.0.0/16"),
    ipaddress.ip_network("100.64.0.0/10"),
    ipaddress.ip_network("::1/128"),
    ipaddress.ip_network("fc00::/7"),
    ipaddress.ip_network("fe80::/10"),
    ipaddress.ip_network("::ffff:0:0/96"),
]


def _is_safe_remote_url(url: str) -> bool:
    """Return True when *url* is an http(s) URL that does not target a
    private/internal address. Used to gate WeasyPrint URL fetches and
    reject logo URLs that point at cloud metadata or LAN services.
    """
    if not url:
        return False
    try:
        parsed = urlparse(url)
    except Exception:
        return False
    if parsed.scheme not in ("http", "https"):
        return False
    if not parsed.hostname:
        return False
    default_port = 443 if parsed.scheme == "https" else 80
    try:
        resolved = socket.getaddrinfo(parsed.hostname, parsed.port or default_port)
    except socket.gaierror:
        return False
    for _, _, _, _, sockaddr in resolved:
        try:
            ip = ipaddress.ip_address(sockaddr[0])
        except ValueError:
            return False
        for network in _BLOCKED_NETWORKS:
            if ip in network:
                return False
        if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved:
            return False
    return True


def _safe_url_fetcher(url: str, timeout: int = 10):
    """WeasyPrint url_fetcher that blocks SSRF-prone targets.

    Falls back to weasyprint.default_url_fetcher for allowed http(s) URLs and
    refuses anything that resolves to a private/internal IP, plus file://,
    data: URIs are still allowed (in-document base64 charts use them).
    """
    if url.startswith("data:"):
        from weasyprint.urls import default_url_fetcher as _default
        return _default(url, timeout=timeout)
    if not _is_safe_remote_url(url):
        raise ValueError(
            f"Refusing to fetch resource at unsafe or private URL: {url[:120]}"
        )
    from weasyprint.urls import default_url_fetcher as _default
    return _default(url, timeout=timeout)


def _safe_accent(accent: str) -> str:
    """Return *accent* if it matches a strict hex/rgb color form, else default.

    Prevents CSS injection through user-controlled accent_color values that
    could break out of the CSS template (e.g. ``red; } body { background:
    url(http://evil)``).
    """
    if isinstance(accent, str) and re.fullmatch(r"#[0-9A-Fa-f]{3,8}", accent):
        return accent
    return "#f59e0b"


def _format_css(theme: str, accent: str, paper_size: str, include_page_numbers: bool) -> str:
    """Format theme CSS with configuration values."""
    css_template = _THEME_CSS.get(theme, _THEME_CSS["professional"])
    page_counter = 'counter(page) " / " counter(pages)' if include_page_numbers else "none"
    return css_template.format(
        accent=accent,
        paper_size=paper_size,
        page_counter=page_counter,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_report(
    content: str,
    config: Any,  # ReportConfig (imported as Any to avoid circular imports)
    metadata: dict[str, Any] | None = None,
) -> bytes:
    """Render Markdown content into PDF bytes using WeasyPrint + Jinja2.

    Args:
        content: Markdown text (typically LLM output).
        config: A ReportConfig dataclass instance.
        metadata: Optional extra metadata dict (e.g. run_id, step_id).

    Returns:
        PDF file content as bytes.

    Raises:
        RuntimeError: If weasyprint is not installed.
    """
    if not HAS_WEASYPRINT:
        raise RuntimeError(
            "weasyprint is not installed. Install with: pip install sandcastle-ai[report]"
        )

    metadata = metadata or {}
    now = datetime.now(timezone.utc)
    accent = _safe_accent(config.accent_color)

    # 1. Preprocess raw markdown
    content = _preprocess_markdown(content)

    # 2. Convert markdown to HTML
    body_html = _markdown_to_html(content)

    # 3. Auto-generate charts from tables with numeric data
    body_html = _auto_charts_from_tables(body_html, accent)

    # 4. Parse explicit ```chart``` code blocks
    body_html = _parse_chart_blocks(body_html, accent)

    # 5. Legacy chart injection (JSON format)
    body_html = _inject_charts(body_html, {"accent_color": accent, **metadata})

    # 6. Parse :::metric KPI rows
    body_html = _parse_metric_rows(body_html)

    # 7. Parse :::info / :::warning / :::success callout boxes
    body_html = _parse_callout_boxes(body_html)

    # 8. Parse ---{text}--- styled dividers
    body_html = _parse_dividers(body_html)

    # 9. Build table of contents
    toc_html = ""
    if config.include_toc:
        toc_html, body_html = _build_toc(body_html)

    # Format CSS
    css = _format_css(config.theme, accent, config.paper_size,
                      config.include_page_numbers)

    # Cover page elements - HTML-escape all user/config supplied strings to
    # prevent stored XSS / HTML injection through ReportConfig fields.
    raw_title = config.title or metadata.get("title", "Report")
    title = _html.escape(str(raw_title))
    subtitle_html = (
        f'<div class="subtitle">{_html.escape(str(config.subtitle))}</div>'
        if config.subtitle else ""
    )
    author_html = (
        f"<div><strong>Author:</strong> {_html.escape(str(config.author))}</div>"
        if config.author else ""
    )
    # Only embed the logo when it points at a safe http(s) host or is a
    # data: URI; otherwise drop it to avoid SSRF/file:// access via WeasyPrint.
    logo_html = ""
    if config.logo_url:
        logo_src = str(config.logo_url)
        if logo_src.startswith("data:") or _is_safe_remote_url(logo_src):
            logo_html = (
                f'<img class="logo" src="{_html.escape(logo_src, quote=True)}" '
                f'alt="Logo">'
            )
        else:
            logger.warning(
                "Refusing to embed logo from unsafe URL: %s", logo_src[:120],
            )
    date_str = now.strftime("%B %d, %Y")

    # Apply Jinja2 template if available, otherwise simple string formatting
    full_html = _REPORT_HTML_TEMPLATE.format(
        css=css,
        logo_html=logo_html,
        title=title,
        subtitle_html=subtitle_html,
        author_html=author_html,
        date=date_str,
        toc_html=toc_html,
        content=body_html,
    )

    # Render to PDF via WeasyPrint
    if config.format == "html":
        return full_html.encode("utf-8")

    # Restrict resource fetching to safe http(s) URLs / data: URIs.
    pdf_bytes = WeasyprintHTML(
        string=full_html, url_fetcher=_safe_url_fetcher,
    ).write_pdf()
    return pdf_bytes


def render_report_html(
    content: str,
    config: Any,
    metadata: dict[str, Any] | None = None,
) -> str:
    """Render Markdown content into an HTML string (no WeasyPrint needed).

    Useful for previewing or when PDF output is not required.
    """
    metadata = metadata or {}
    now = datetime.now(timezone.utc)
    accent = _safe_accent(config.accent_color)

    # Full transformation pipeline (same as render_report)
    content = _preprocess_markdown(content)
    body_html = _markdown_to_html(content)
    body_html = _auto_charts_from_tables(body_html, accent)
    body_html = _parse_chart_blocks(body_html, accent)
    body_html = _inject_charts(body_html, {"accent_color": accent, **metadata})
    body_html = _parse_metric_rows(body_html)
    body_html = _parse_callout_boxes(body_html)
    body_html = _parse_dividers(body_html)

    toc_html = ""
    if config.include_toc:
        toc_html, body_html = _build_toc(body_html)

    css = _format_css(config.theme, accent, config.paper_size,
                      config.include_page_numbers)

    raw_title = config.title or metadata.get("title", "Report")
    title = _html.escape(str(raw_title))
    subtitle_html = (
        f'<div class="subtitle">{_html.escape(str(config.subtitle))}</div>'
        if config.subtitle else ""
    )
    author_html = (
        f"<div><strong>Author:</strong> {_html.escape(str(config.author))}</div>"
        if config.author else ""
    )
    logo_html = ""
    if config.logo_url:
        logo_src = str(config.logo_url)
        if logo_src.startswith("data:") or _is_safe_remote_url(logo_src):
            logo_html = (
                f'<img class="logo" src="{_html.escape(logo_src, quote=True)}" '
                f'alt="Logo">'
            )
        else:
            logger.warning(
                "Refusing to embed logo from unsafe URL: %s", logo_src[:120],
            )
    date_str = now.strftime("%B %d, %Y")

    return _REPORT_HTML_TEMPLATE.format(
        css=css,
        logo_html=logo_html,
        title=title,
        subtitle_html=subtitle_html,
        author_html=author_html,
        date=date_str,
        toc_html=toc_html,
        content=body_html,
    )
