import {
  MessageSquare,
  Mail,
  Users,
  GitBranch,
  BookOpen,
  BarChart3,
  Cloud,
  Headphones,
  HardDrive,
  Database,
  Webhook,
  Building2,
  Wrench,
  Snowflake,
  CircleDot,
  CreditCard,
  Phone,
  Send,
  MessageCircle,
  Table2,
  LayoutGrid,
  Target,
  Gamepad2,
  Brain,
  Cpu,
  Box,
  Server,
  DatabaseZap,
  Crosshair,
  MailCheck,
  Rocket,
  CloudCog,
  Flame,
  Search,
  AudioLines,
  Zap,
  ShoppingCart,
  Receipt,
  Calendar,
  Figma,
  Activity,
  DollarSign,
  FileSignature,
  AlertTriangle,
  Link2,
  UserCheck,
  FolderOpen,
  Terminal,
  Code2,
  Globe,
  type LucideIcon,
} from "lucide-react";

/** Map tool `icon` string to a lucide-react component. */
export const TOOL_ICON_MAP: Record<string, LucideIcon> = {
  slack: MessageSquare,
  jira: BookOpen,
  github: GitBranch,
  mail: Mail,
  notion: BookOpen,
  hubspot: BarChart3,
  salesforce: Cloud,
  zendesk: Headphones,
  teams: Users,
  gdrive: HardDrive,
  database: Database,
  webhook: Webhook,
  sap: Building2,
  servicenow: Wrench,
  snowflake: Snowflake,
  mongodb: CircleDot,
  stripe: CreditCard,
  twilio: Phone,
  sendgrid: Send,
  intercom: MessageCircle,
  // New integrations
  "google-sheets": Table2,
  airtable: LayoutGrid,
  linear: Target,
  discord: Gamepad2,
  openai: Brain,
  anthropic: Cpu,
  "aws-s3": Box,
  redis: Server,
  supabase: DatabaseZap,
  pinecone: Crosshair,
  resend: MailCheck,
  vercel: Rocket,
  "cloudflare-workers": CloudCog,
  firecrawl: Flame,
  tavily: Search,
  elevenlabs: AudioLines,
  zapier: Zap,
  shopify: ShoppingCart,
  quickbooks: Receipt,
  calendly: Calendar,
  whatsapp: MessageCircle,
  figma: Figma,
  datadog: Activity,
  plaid: DollarSign,
  docusign: FileSignature,
  pagerduty: AlertTriangle,
  "mcp-bridge": Link2,
  "human-input": UserCheck,
  filesystem: FolderOpen,
  shell: Terminal,
  "python-runtime": Code2,
  "code-interpreter": Code2,
  browser: Globe,
};

/** Category -> Tailwind color classes (bg for icon wrapper, text for icon). */
export const CATEGORY_COLORS: Record<string, { bg: string; text: string }> = {
  communication: { bg: "bg-blue-500/15", text: "text-blue-500" },
  project_management: { bg: "bg-purple-500/15", text: "text-purple-500" },
  crm: { bg: "bg-amber-500/15", text: "text-amber-500" },
  data: { bg: "bg-emerald-500/15", text: "text-emerald-500" },
  erp: { bg: "bg-orange-500/15", text: "text-orange-500" },
  payments: { bg: "bg-violet-500/15", text: "text-violet-500" },
  general: { bg: "bg-gray-500/15", text: "text-gray-400" },
  ai: { bg: "bg-pink-500/15", text: "text-pink-500" },
  devops: { bg: "bg-cyan-500/15", text: "text-cyan-500" },
};

/** Human-readable category labels. */
export const CATEGORY_LABELS: Record<string, string> = {
  communication: "Communication",
  project_management: "Project Mgmt",
  crm: "CRM",
  data: "Data",
  erp: "ERP",
  payments: "Payments",
  general: "General",
  ai: "AI",
  devops: "DevOps",
};
